CREATE TABLE CLIENTE

(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO VARCHAR(150),
ENDERECO2 VARCHAR(150),
CIDADE VARCHAR(50),
BAIRRO VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
CREDITO FLOAT,
COMPRAS FLOAT,
PRIMEIRA_COMPRA BIT(1));